name: ⭐️ Proposal
description: Suggest an idea for a new feature
title: "✨ Proposal: "
labels: ["proposal", "Status: Triage"]
body:
- type: textarea
  attributes:
    label: Describe the inspiration for your proposal
    description: Does the proposal address a problem you're facing?
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the proposal
    description: Please be as clear as possible and use examples.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: Can the functionality you're proposal be achieved with the features available today?
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: Is there anything else related to your proposal that you'd like to cover?
  validations:
    required: false
